FROM tensorflow/tensorflow:latest-py3

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    PYTHONPATH=/app
WORKDIR /app

RUN apt-get update && \
    apt-get -y install curl && \
    pip install pipenv

COPY Pip* ./

RUN pipenv install --three --deploy --system
